### ISSUE TITLE
New module to manage "Cloud connector"

### ISSUE THREAD

**Issue by neikei** [IBM/ansible-power-hmc#114]
**Is your feature request related to a problem? Please describe.**
The cloud connector has been an important feature of HMC since the introduction of PEP2.0 and this is why it should be possible to handle the connector via Ansible.

```bash
# CLI options
chsvc -s cloudconn -o {start | stop | restart} [-k key] [--http proxy-URI] [--socks proxy-URI]
```

**Describe the solution you'd like**
A new module is needed to handle the cloud connector.

```yaml
cloud_connector:
  key: ""
  state: "" # [started, stopped, restarted)
  http_proxy: ""
  socks_proxy: ""
```

**Additional context**
Official IBM documentation: https://www.ibm.com/docs/en/power10?topic=commands-chsvc
