### ISSUE TITLE
AIX Installation stalls at HMC code 0c31

### ISSUE THREAD

**Issue by mshakeer03** [IBM/ansible-power-hmc#121]
Trying to install AIX using NIM, the LPAR profile is already created with virtual network and FC adapters, the installation is stuck at **0c31** HMC code. The Boot mode and Keylock position is set to **_Normal_**

**Comment by mshakeer03** [comment]
Here is the ansible task
```yml
    - name: Beign AIX installation for LPAR {{ lpar_name }}
      ibm.power_hmc.powervm_lpar_instance:
        hmc_host: '{{ hmc_host }}'
        hmc_auth:
          username: "hmc_user"
          password: "hmc_pass"
        system_name: "{{ system_name }}"
        vm_name: "{{ lpar_name }}"
        install_settings:
          vm_ip: "{{ lpar_ip }}"
          nim_ip: "{{ nim_ip }}"
          nim_gateway: "{{ nim_gateway }}"
          nim_subnetmask: "{{ nim_subnetmask }}"
        action: install_os
      register: install_details 
```
