### ISSUE TITLE
Add action_groups into meta/runtime.yml

### ISSUE THREAD

**Issue by aklyachkin** [IBM/ansible-power-hmc#122]
Ansible supports module_defaults sections to define default settings for modules. See https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_module_defaults.html

Now I can define this module_defaults for each module. By adding action_groups into runtime.yml it will be possible to define module_defaults for all modules in one statement.

Situation now:

```yaml
---
- name: Sample playbook
  module_defaults:
    ibm.power_hmc.hmc_command:
      hmc_host: myhmc
      hmc_auth:
        username: hscroot
        password: abc123
    ibm.power_hmc.hmc_user:
      hmc_host: myhmc
      hmc_auth:
        username: hscroot
        password: abc123
```

Situation after the change:

```yaml
---
- name: Sample playbook
  module_defaults:
    group/ibm.power_hmc.modules:
      hmc_host: myhmc
      hmc_auth:
        username: hscroot
        password: abc123
```

Sample of meta/runtime.yml:

```yaml
---
action_groups:
  ibm.power_hmc.modules:
  - firmware_update
  - hmc_command
  - hmc_pwdpolicy
  - hmc_update_upgrade
  - hmc_user
  - power_system
  - powervm_dlpar
  - powervm_lpar_instance
  - powervm_lpar_migration
  - vios
requires_ansible: '>=2.13'
```
