### ISSUE TITLE
Allow multiple virt_networks and volumes on lpar creation

### ISSUE THREAD

**Issue by Mikesch-mp** [IBM/ansible-power-hmc#45]
**Is your feature request related to a problem? Please describe.**
Most LPARs i have to create have a mirrorred rootvg and at least 2 network interfaces in different vlans. it would be wonderfull if it is possible to add them at creation.

**Describe the solution you'd like**
For the virtual network interfaces something like a list of dictionaries to configure them
```
      virt_network_config:
        interface0:
          network_name: VLAN1233-ETHERNET0
          slot_number: 49
        interface1:
          network_name: VLAN1234-ETHERNET0
          slot_number: 50
```
and same for volume configuration (with name or size)

```
      volume_config:
        volume0:
          vios_name: zepp31-vios1
          volume_name: hdisk4
        volume1:
          vios_name: zepp31-vios1
          volume_name: hdisk5
```
**Describe alternatives you've considered**
Create LPARs with one interface and 1 volume and then use the HMC UI to add other interface + volume.
Takes a lot of time and is slow manualy done :(
