### ISSUE TITLE
Allow login into HMC with certificate instead of password

### ISSUE THREAD

**Issue by christian-naenny** [IBM/ansible-power-hmc#53]
**Is your feature request related to a problem? Please describe.**
In our organization we strive to replace passwords with certificate files. The UNIX engineering team responsible for the IBM Power Infrastructure was not very pleased when I asked for a login with username/password to be able use the powervm_lpar_instance module.

**Describe the solution you'd like**
Instead of providing the parameters username and password for hmc_auth it should be possible to provide the username and the path to a certificate file to be used for login into the HMC.
Example to shutdown an LPAR:
```
- name: Shutdown a logical partition
  powervm_lpar_instance:
      hmc_host: '{{ inventory_hostname }}'
      hmc_auth:
         username: '{{ ansible_user }}'
         certificate: '{{ path_to_certfile }}'
      system_name: <system_name>
      vm_name: <vm_name>
      action: shutdown
```

**Describe alternatives you've considered**
Until the login with a certificate file is possible, we don't have much of an alternative to a login with username/password
