### ISSUE TITLE
powervm_lpar_instance install_os action is stuck with HMC code 0608

### ISSUE THREAD

**Issue by stone1229** [IBM/ansible-power-hmc#86]
**Describe the bug**
OS installation using powervm_lpar_instance module is stuck with code 0608 on HMC.  Then installation fails with timeout error.

> "msg": "AIX Installation failed even after waiting for 30 mins and the reference code is 0608"

**To Reproduce**
Command : 
ansible-playbook lpar_install.yml

Playbook : 

```
- hosts: localhost
  become: yes
  gather_facts: no

  tasks:

  - name: Launch AIX installation
    ibm.power_hmc.powervm_lpar_instance:
      hmc_host: "{{ hmc_host }}"
      hmc_auth:
        username: "{{ vault.hmc.username }}"
        password: "{{ vault.hmc.password }}"
      action: install_os
      system_name: "{{ client_mngsyst }}"
      vm_name: "{{ nim_client }}"
      install_settings:
        vm_ip: "{{ nim_client_ip }}"
        nim_ip: "{{ nim_server_ip }}"
        nim_gateway: "{{ nim_client_gw }}"
        nim_subnetmask: "{{ nim_client_nm }}"
        nim_vlan_id: "{{ vlan_number }}"
        timeout: 30
```

**Expected behavior**
AIX LPAR is started and installed.

**Environment (please complete the following information):**
 - HMC: 

```
 hmc# lshmc -V
"version= Version: 9
 Release: 2
 Service Pack: 952
HMC Build level 2201042318
MH01874 - HMC V9R2 M951
MH01884 - iFix for HMC V9R2 M950
MH01890 - iFix for HMC V9R2 M951
MH01905 - HMC V9R2 M952
MH01917 - iFix for HMC V9R2 M952
","base_version=V9R2
"
```

 - Python Version : Python 3.6.8

 - OpenSSH Version : 1.0.2k

**Additional context**
Installation is working fine when we use   ibm.power_hmc.hmc_command module with lpar_netboot : 

```
- name: Launch AIX installation
  ibm.power_hmc.hmc_command:
    hmc_host: "{{ hmc_host }}"
    hmc_auth:
      username: "{{ vault.hmc.username }}"
      password: "{{ vault.hmc.password }}"
    cmd: "lpar_netboot -t ent -s auto -d auto -S {{ nim_server_ip }} -G {{ nim_client_gw }} -K {{ nim_client_nm }} -C {{ nim_client_ip }} {{ nim_client }} {{ hmc_boot_profile }} {{ client_mngsyst }}"
```
