### ISSUE TITLE
Get all facts from every managed system / lpar

### ISSUE THREAD

**Issue by MalfuncEddie** [IBM/ansible-power-hmc#88]
**Is your feature request related to a problem? Please describe.**

I would like to have a "hmc scanner" like report in json (facts) from the hmc

**Describe the solution you'd like**

Either I am missing something but it seems you cannot do

- list all managed systems
- list all lpars of a managed system
if this works I would be able to 
```
loop every managed system 
  get lpars
    loop  lpar 
      get facts
```
  

**Describe alternatives you've considered**
read hmcscanner xls with a python script

**Comment by AnilVijayan** [comment]
Thanks for letting us know your requirement. We do have some options to iterate through the Managed Systems and then to partition.
We are also working on some more improvement on that coming Dec release.

Please check if below solution works for you,
1. Create a dynamic inventory config file as below,

```
cat server_iterate.power_hmc.yml
plugin: ibm.power_hmc.powervm_inventory
hmc_hosts:
  "9.3.XX.XXX":
    user: hscroot
    password: XXXXXXXX
compose:
  server_name: SystemName
keyed_groups:
  - prefix: "server_group_"
    key: SystemName

```

2. Use the above inventory to run the below playbook to list the facts of logical partitions,

```
---
- hosts: server_group_*
  collections:
  - ibm.power_hmc
  connection: local

  tasks:
  - powervm_lpar_instance:
      hmc_host: "9.3.XX.XXX"
      hmc_auth:
        username: hscroot
        password: XXXXXXX
      system_name: "{{ server_name }}"
      vm_name: "{{ inventory_hostname }}"
      state: facts

```

**Comment by christophegehin** [comment]
Hello

I'm trying to use the previous sample to get a dynamic inventory.
Here's my yml inventory file : 
plugin: ibm.power_hmc.powervm_inventory
hmc_hosts:
 'HMC1':
    user: 'hscroot'
    password: 'xxxxxxxxxxx'
compose:
  frame_name: SystemName
keyed_groups:
  - prefix: "frame_"
    key: SystemName
filters:
  PartitionName: lpar1

I test the yml with that command : 
ansible-inventory -i tof.power_hmc.yml --list

I get an error : [WARNING]:  * Failed to parse tof.power_hmc.yml with auto plugin: Could not set frame_name for host lpar1: 'SystemName' is undefined

Could you help me ?

Thanks you.

**Comment by naveenkandakur** [comment]
Looking at your yaml content and error message, you are trying on HMC version <= 1020 and you are using older power_hmc ansible content, which doesn't support SystemName parameter, To address this issue we have come up with the solution in the latest power_hmc collection version 1.7 
 
 So, please use the latest content of the power_hmc collection version 1.7 from _https://galaxy.ansible.com/ibm/power_hmc_

 We have enhanced the dynamic inventory plugin in the latest content to include a Managed systems group and support for SystemName parameter in the HMC versions <=1020, please refer the documentation page for more details of the latest content _https://ibm.github.io/ansible-power-hmc/release_notes.html_.

 Below is the sample you can use to list all managed systems and their lpars.
```
plugin: ibm.power_hmc.powervm_inventory
hmc_hosts:
  - hmc: "<HMC_IP>"
    user: <username>
    password: <passwd>
filter:
    PartitionName: 'lpar1'
group_lpars_by_managed_system: false
keyed_groups:
  - prefix: "frame_"
    key: SystemName
compose:
  frame_name: SystemName
```

Please let me know if you face any other issues with latest content.
