### ISSUE TITLE
Ansible PowerPC HMC: LPAR creation failed

### ISSUE THREAD

**Issue by hutepa** [IBM/ansible-power-hmc#90]
- LPAR creation using Ansible fails with error "urllib.error.HTTPError: HTTP Error 500"
- Ansible Collection: ibm.power_hmc
- Ansible Module: powervm_lpar_instance
- create_lapr.yml:

```
----

- name: Create an AIX/Linux lpar instance and install OS
  hosts: '{{ myhost }}'
  collections:
    - ibm.power_hmc
  connection: local

  tasks:
    - name: Create lpar instance 
      powervm_lpar_instance:
        hmc_host: '{{ inventory_hostname }}'
        hmc_auth:
          username: 'user'
          password: 'pass'
        system_name: 'xx'
        vm_name: 'test001'
        virt_network_config:
          - network_name: 'xx'
        npiv_config:
          - vios_name: 'xx'
            fc_port: 'xx'
        os_type: aix_linux
        state: present
```

-ansible.cfg
```
[defaults]
host_key_checking = False
remote_tmp = /tmp/test/

[galaxy]
server_list = automation_hub

[galaxy_server.automation_hub]
url=https://cloud.redhat.com/api/automation-hub/
auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token

token=''
```

-  Ansible full trace: https://pastebin.com/qBHRfaPU

# ansible --version
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mahmab/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/mahmab/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:52:37) [GCC 8.5.0 [20210514](https://access.redhat.com/support/cases/#/case/20210514) (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

# cat /etc/system-release
Red Hat Enterprise Linux release 8.6 (Ootpa)
