### ISSUE TITLE
ibm.power_hmc.powervm_inventory SystemName name missing of "identify_unknown_by" lpars

### ISSUE THREAD

**Issue by MalfuncEddie** [IBM/ansible-power-hmc#94]
**Describe the bug**
When gathering facts of an HMC I have added the not running lpars. I assumed that even if the lpar is powered off the SystemName of where the lpar is would be added

```
plugin: ibm.power_hmc.powervm_inventory
hmc_hosts:
  - hmc: "xxx"
    user: "xxx"
    password: "xxx"
identify_unknown_by: PartitionName
compose:
  server_name: SystemName
keyed_groups:
  - prefix: "server_group"
    key: SystemName
  - prefix: "partition_type"
    key: PartitionType
```

**To Reproduce**

**Expected behavior**
SystemName should be available even if the lpar is powered off

**Additional context**

For reporting purposes I am gathering facts of the lpars via the HMC. I would suspect that gathering fact of an powered off system should work yet it needs the SystemName  and that is not inserted into the inventory test
