### ISSUE TITLE
power_lpar_instance HMC fails to log in

### ISSUE THREAD

**Issue by saffer58** [IBM/ansible-power-hmc#95]
When running the module "power_lpar_instance" to power down a lpar, I get a HMC login failure. We run ssh keys and have a valid password. Neither allow access to the HMC.
This behaviour does not occur on the "power_lpar_migation".
The ansible server can log into our HMC without any issue. I tested this across 4 HMCs and all four have experienced the same issue.
Unless the documentation is wrong, there appears to be an issue with the authentication section.

`fatal: [hmcdc1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "shutdown",
            "advanced_info": null,
            "all_resources": null,
            "delete_vdisks": null,
            "hmc_auth": {
                "password": null,
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "hmc_host": "hmcdc1",
            "iIPLsource": null,
            "keylock": null,
            "max_mem": null,
            "max_proc": null,
            "max_proc_unit": null,
            "max_virtual_slots": null,
            "mem": null,
            "min_mem": null,
            "min_proc": null,
            "min_proc_unit": null,
            "npiv_config": null,
            "os_type": null,
            "physical_io": null,
            "proc": null,
            "proc_compatibility_mode": null,
            "proc_mode": null,
            "proc_unit": null,
            "prof_name": null,
            "retain_vios_cfg": null,
            "shared_proc_pool": null,
            "state": null,
            "system_name": "MYMANAGED_SERVER",
            "virt_network_config": null,
            "vm_name": "aixgold",
            "volume_config": null,
            "weight": null
        }
    },
    "msg": "Logon to HMC failed"
}
`
```
---
- name: HMC poweroff
  hosts: HMC
  collections:
      - ibm.power_hmc
  connection: local

  tasks:

  - name: Shutdown a logical partition.
    powervm_lpar_instance:
        hmc_host: hmcdc1
        hmc_auth:
           username: '{{ ansible_user }}'
           password: *********
        system_name: MYMANAGED_SERVER
        vm_name: aixgold
        action: shutdown

```
